export const ths = {
  date: '日期',
  mark: '索引',
  serious: '认真',
  hunger: '饱腹',
  san: 'san',
  hp: '疲劳',
  freeTime: '空闲',
  sleepTime: '睡时',
  // hasImportantThing: '重要',
  hasSport: '运动',
  hasRead: '看书',
  hasKindle: 'kindle',
  fallAsleep: '入睡'
};
export const thLabels = {
  date: '日期',
  date1: '日期',
  date2: '日期',
  date3: '日期',
  date4: '日期',
  date5: '日期',
  date6: '日期',
  date7: '日期',
  date8: '日期',
  date9: '日期',
  date10: '日期',
  date11: '日期',
  date12: '日期'
};
export const th = [
  '日期',
  '索引',
  '认真程度',
  '饱腹度',
  'san值',
  '疲劳度',
  '空闲时间',
  '睡觉时间',
  '是否有重要之事',
  '是否有运动',
  '是否看书',
  '是否看kindle',
  '容易入睡'
];
export const testData = [
  {
    date: '7.1',
    mark: '索引',
    serious: '1',
    hunger: '1',
    san: '2',
    hp: '3',
    freeTime: '6',
    sleepTime: '23:00',
    hasImportantThing: '0',
    hasSport: '0',
    hasRead: '0',
    hasKindle: '1',
    fallAsleep: '容易'
  },
  {
    date: '7.2',
    mark: '索引',
    serious: '1',
    hunger: '1',
    san: '2',
    hp: '3',
    freeTime: '6',
    sleepTime: '23:00',
    hasImportantThing: '0',
    hasSport: '0',
    hasRead: '0',
    hasKindle: '1',
    fallAsleep: '容易'
  },
  {
    date: '7.3',
    mark: '索引',
    serious: '1',
    hunger: '1',
    san: '2',
    hp: '3',
    freeTime: '6',
    sleepTime: '23:00',
    hasImportantThing: '0',
    hasSport: '0',
    hasRead: '0',
    hasKindle: '1',
    fallAsleep: '容易'
  },
  {
    date: '7.4',
    mark: '索引',
    serious: '1',
    hunger: '1',
    san: '2',
    hp: '3',
    freeTime: '6',
    sleepTime: '23:00',
    hasImportantThing: '0',
    hasSport: '0',
    hasRead: '0',
    hasKindle: '1',
    fallAsleep: '容易'
  },
  {
    date: '7.5',
    mark: '索引',
    serious: '1',
    hunger: '1',
    san: '2',
    hp: '3',
    freeTime: '6',
    sleepTime: '23:00',
    hasImportantThing: '0',
    hasSport: '0',
    hasRead: '0',
    hasKindle: '1',
    fallAsleep: '容易'
  }
];

export const rs = {
  status: 0,
  data: [
    {
      createdTime: '2018-07-26T05:07:06.093Z',
      _id: '5b51777c71ab5c56ece18f34',
      author_name: '',
      date: '2018-07-19',
      mark: '拿回苏婆',
      serious: '2',
      hunger: '2',
      san: '2',
      hp: '3',
      freeTime: '3',
      sleepTime: '0点48',
      hasImportantThing: '0',
      hasSport: '1',
      hasRead: '0',
      hasKindle: '0',
      fallAsleep: '较难-苏婆风扇还是没修好',
      __v: 0
    },
    {
      createdTime: '2018-07-26T05:07:06.093Z',
      _id: '5b534fc871ab5c56ece18f35',
      author_name: '',
      date: '2018-07-20',
      mark: '杨伏敖平聚餐玩骰子',
      serious: '2',
      hunger: '2',
      san: '1',
      hp: '2',
      freeTime: '4',
      sleepTime: '2点47',
      hasImportantThing: '0',
      hasSport: '0',
      hasRead: '0',
      hasKindle: '0',
      fallAsleep: '容易',
      __v: 0
    },
    {
      createdTime: '2018-07-26T05:07:06.093Z',
      _id: '5b53c6e871ab5c56ece18f36',
      author_name: '',
      date: '2018-07-21',
      mark: '拔牙，这次很快',
      serious: '3',
      hunger: '2',
      san: '2',
      hp: '2',
      freeTime: '5',
      sleepTime: '23点48',
      hasImportantThing: '0',
      hasSport: '0',
      hasRead: '0',
      hasKindle: '1',
      fallAsleep: '容易',
      __v: 0
    },
    {
      createdTime: '2018-07-26T05:07:06.093Z',
      _id: '5b5518ef71ab5c56ece18f37',
      author_name: '',
      date: '2018-07-22',
      mark: '网吧嵌59和查牛姨',
      serious: '2',
      hunger: '2',
      san: '2',
      hp: '1',
      freeTime: '7',
      sleepTime: '22:38',
      hasImportantThing: '0',
      hasSport: '0',
      hasRead: '0',
      hasKindle: '1',
      fallAsleep: '容易',
      __v: 0
    },
    {
      createdTime: '2018-07-26T05:07:06.093Z',
      _id: '5b566cd371ab5c56ece18f38',
      author_name: '',
      date: '2018-07-23',
      mark: '肉体关系的思考',
      serious: '2',
      hunger: '2',
      san: '1',
      hp: '2',
      freeTime: '3.5',
      sleepTime: '0点28',
      hasImportantThing: '0',
      hasSport: '0',
      hasRead: '1',
      hasKindle: '0',
      fallAsleep: '容易',
      __v: 0
    },
    {
      createdTime: '2018-07-26T05:07:06.093Z',
      _id: '5b57bad971ab5c56ece18f39',
      author_name: '',
      date: '2018-07-24',
      mark: '汉化组选新坑',
      serious: '2',
      hunger: '2',
      san: '2',
      hp: '2',
      freeTime: '2',
      sleepTime: '23点28',
      hasImportantThing: '0',
      hasSport: '0',
      hasRead: '0',
      hasKindle: '1',
      fallAsleep: '容易',
      __v: 0
    },
    {
      createdTime: '2018-07-26T05:07:06.093Z',
      _id: '5b5a805903a0d46a1ab3da56',
      authorName: '',
      date: '2018-07-26',
      mark: '加班到0点25',
      serious: '2',
      hunger: '2',
      san: '1',
      hp: '1',
      freeTime: '-1',
      sleepTime: '2点38',
      hasImportantThing: '0',
      hasSport: '0',
      hasRead: '0',
      hasKindle: '0',
      fallAsleep: '容易',
      __v: 0
    }
  ]
};
