// export const thLabels = {
//   date: '日期',
//   mark: '索引',
//   serious: '认真程度',
//   hunger: '饱腹度',
//   san: 'san值',
//   hp: '疲劳度',
//   freeTime: '空闲时间',
//   sleepTime: '睡觉时间',
//   hasImportantThing: '是否有重要之事',
//   hasSport: '是否有运动',
//   hasRead: '是否看书',
//   hasKindle: '是否看kindle',
//   fallAsleep: '容易入睡'
// };
export const thLabels = {
  date: '日期',
  date1: '日期',
  date2: '日期',
  date3: '日期',
  date4: '日期',
  date5: '日期',
  date6: '日期',
  date7: '日期',
  date8: '日期',
  date9: '日期',
  date10: '日期',
  date11: '日期',
  date12: '日期'
};
export const th = [
  '日期',
  '索引',
  '认真程度',
  '饱腹度',
  'san值',
  '疲劳度',
  '空闲时间',
  '睡觉时间',
  '是否有重要之事',
  '是否有运动',
  '是否看书',
  '是否看kindle',
  '容易入睡'
];
export const testData = [
  {
    date: '7.1',
    mark: '索引',
    serious: '1',
    hunger: '1',
    san: '2',
    hp: '3',
    freeTime: '6',
    sleepTime: '23:00',
    hasImportantThing: '0',
    hasSport: '0',
    hasRead: '0',
    hasKindle: '1',
    fallAsleep: '容易'
  },
  {
    date: '7.2',
    mark: '索引',
    serious: '1',
    hunger: '1',
    san: '2',
    hp: '3',
    freeTime: '6',
    sleepTime: '23:00',
    hasImportantThing: '0',
    hasSport: '0',
    hasRead: '0',
    hasKindle: '1',
    fallAsleep: '容易'
  },
  {
    date: '7.3',
    mark: '索引',
    serious: '1',
    hunger: '1',
    san: '2',
    hp: '3',
    freeTime: '6',
    sleepTime: '23:00',
    hasImportantThing: '0',
    hasSport: '0',
    hasRead: '0',
    hasKindle: '1',
    fallAsleep: '容易'
  },
  {
    date: '7.4',
    mark: '索引',
    serious: '1',
    hunger: '1',
    san: '2',
    hp: '3',
    freeTime: '6',
    sleepTime: '23:00',
    hasImportantThing: '0',
    hasSport: '0',
    hasRead: '0',
    hasKindle: '1',
    fallAsleep: '容易'
  },
  {
    date: '7.5',
    mark: '索引',
    serious: '1',
    hunger: '1',
    san: '2',
    hp: '3',
    freeTime: '6',
    sleepTime: '23:00',
    hasImportantThing: '0',
    hasSport: '0',
    hasRead: '0',
    hasKindle: '1',
    fallAsleep: '容易'
  }
];
